// Code generated by cli. DO NOT EDIT
package docs

import _ "github.com/todennus/oauth2-service/adapter/rest"

// @title Todennus API Endpoints
// @version 1.0
// @description This is Todennus - An Open ID Connect and OAuth2 Provider

// @securityDefinitions.oauth2.application OAuth2Application
// @tokenUrl /oauth2/token
// @scope.offline_access Maintain access to the resource even if the user is not present
// @scope.todennus/read:user.profile Grant read-only access to the user's profile
// @scope.todennus/read:user.avatar Grant read-only access to the user's avatar
// @scope.todennus/update:user.avatar Grant permission to update the user's avatar
// @scope.todennus/read:client.profile Grant read-only access to the client's profile
// @scope.todennus/create:client Grant permission to create new clients
// @scope.todennus/app:read:client.owner Grant read-only access to the client's owner id
// @scope.todennus/app:read:client.profile Grant read-only access to the client's profile
// @scope.todennus/admin:read:user.profile Grant read-only access to all users' profiles
// @scope.todennus/admin:validate:user Grant permission to validate all users' credentials
// @scope.todennus/admin:create:user Grant permission to create new users
// @scope.todennus/admin:read:client.profile Grant read-only access to all client profiles
// @scope.todennus/admin:validate:client Grant permission to validate the client's credentials
// @scope.todennus/admin:create:client Grant permission to create new clients
// @scope.todennus/admin:register:file.policy Grant permission to register file upload policy
// @scope.todennus/admin:create:file.presigned_url Grant permission to create file presigned url
// @scope.todennus/admin:change:file.refcount Grant permission to change ref count of file ownership
