// Package docs Code generated by cli. DO NOT EDIT
package docs

import _ "github.com/todennus/oauth2-service/adapter/rest"

// @title Todennus API Endpoints
// @version 1.0
// @description This is Todennus - An Open ID Connect and OAuth2 Provider

// @securityDefinitions.oauth2.application OAuth2Application
// @tokenUrl /oauth2/token
// @scope.offline_access Maintain access to resource even if user is not present
// @scope.todennus/read:user.profile Grant read-only access to user profile
// @scope.todennus/read:client.profile Grant read-only access to client profile
// @scope.todennus/create:client Grant permission to create a client
// @scope.todennus/app:read:client.owner Grant read-only access to client owner id
// @scope.todennus/app:read:client.profile Grant read-only access to client profile
// @scope.todennus/admin:read:user.profile Grant admin read-only access to user profile
// @scope.todennus/admin:validate:user Grant admin permission to validate user credentials
// @scope.todennus/admin:create:user Grant admin permission to create a new user
// @scope.todennus/admin:read:client.profile Grant admin read-only access to client profile
// @scope.todennus/admin:validate:client Grant admin permission to validate client
// @scope.todennus/admin:create:client Grant admin permission to create a client
